services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    mem_limit: 500m
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: y@tm.org
      PGADMIN_DEFAULT_PASSWORD: pass

  postgis:
    image: postgis/postgis:latest
    container_name: postgis
    restart: always
    mem_limit: 1.5g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres