version: "0"
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_subnetwork
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: yonatan@tempmail.org
      PGADMIN_DEFAULT_PASSWORD: pass

  postgis:
    image: postgres
    container_name: postgres_subnetwork
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass